# Generated by Django 5.2.7 on 2025-12-04 20:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('generic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('medicine_type', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('other', 'Other')], default='tablet', max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reorder_level', models.IntegerField(default=10, help_text='Minimum stock level before reordering')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('case_no', models.AutoField(primary_key=True, serialize=False)),
                ('case', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone_no', models.CharField(max_length=10)),
                ('doctor', models.CharField(choices=[('dr_1', 'Dr. Ami Bhatt'), ('dr_2', 'Dr. Kaushal Bhatt')], max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(help_text='When the follow-up is scheduled')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('checkin_time', models.DateTimeField(blank=True, help_text='When the patient checked in', null=True)),
                ('checkin_status', models.CharField(blank=True, choices=[('early', 'Early'), ('on_time', 'On Time'), ('late', 'Late')], max_length=20, null=True)),
                ('checkin_minutes_difference', models.IntegerField(blank=True, help_text='Signed minutes difference: checkin - scheduled', null=True)),
                ('checkin_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_done', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='Anand_Clinic.patient')),
            ],
            options={
                'verbose_name': 'Follow up',
                'verbose_name_plural': 'Follow ups',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('early', 'Early'), ('on_time', 'On Time'), ('late', 'Late')], default='on_time', max_length=20)),
                ('minutes_difference', models.IntegerField(default=0, help_text='Signed minutes difference: checkin - scheduled')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='Anand_Clinic.followup')),
            ],
            options={
                'ordering': ['-checkin_time'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField(default=0)),
                ('case', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prescribed_by_ami', models.BooleanField(default=False)),
                ('prescribed_by_kaushal', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('gu', 'Gujarati')], default='en', max_length=5)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_prescriptions', to='Anand_Clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='NextDayInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_no', models.CharField(max_length=50)),
                ('no_of_pill', models.CharField(max_length=20)),
                ('dose', models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five')], max_length=10)),
                ('time_of_day', models.CharField(choices=[('Day', 'Day'), ('Morning', 'Morning'), ('Night', 'Night')], max_length=20)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_day_instructions', to='Anand_Clinic.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='FirstDayInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_of_bottle', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('no_of_pill', models.CharField(max_length=20)),
                ('time_of_day', models.CharField(choices=[('Day', 'Day'), ('Morning', 'Morning'), ('Night', 'Night')], max_length=20)),
                ('special_instruction', models.TextField(blank=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_day_instructions', to='Anand_Clinic.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('receptionist', 'Receptionist')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Anand_Clinic.medicine')),
            ],
        ),
    ]
